### ISSUE TITLE
Opportunity lists in Salesforce

### ISSUE THREAD

**Issue by EllenLeeds** [matthiaskjordan/email_process#1]
<img width="780" alt="screen shot 2016-12-05 at 8 55 47 pm" src="https://cloud.githubusercontent.com/assets/19541978/20913512/63a4cd86-bb2d-11e6-8f95-84640ce96860.png">

**Comment by matthiaskjordan** [comment]
Thanks, Ellen!

**Comment by matthiaskjordan** [comment]
Spoke to Jillian, and she showed me how to build these in Pardot directly, rather than in Salesforce! 

See List section in commit 77e1fad
